# Generated by Django 5.2 on 2025-04-10 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highestedu',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobcategory',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobdescription',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='max_salary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='min_salary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='shift',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(default='', upload_to='app/img/company'),
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(default='', max_length=250)),
                ('companyname', models.CharField(default='', max_length=250)),
                ('companyaddress', models.CharField(default='', max_length=250)),
                ('jobdescription', models.TextField(default='', max_length=500)),
                ('qualification', models.CharField(default='', max_length=250)),
                ('responsibities', models.CharField(default='', max_length=250)),
                ('location', models.CharField(default='', max_length=250)),
                ('companywebsite', models.CharField(default='', max_length=250)),
                ('companyemail', models.CharField(default='', max_length=250)),
                ('companycontact', models.CharField(default='', max_length=250)),
                ('salarypackage', models.CharField(default='', max_length=250)),
                ('experience', models.IntegerField()),
                ('logo', models.ImageField(default='', upload_to='app/img/jobpost')),
                ('company_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(default='', max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('min_salary', models.CharField(max_length=200)),
                ('max_salary', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='app/resume')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobdetails')),
            ],
        ),
    ]
